interface SalesPitchProps {
    salesPitch: string;
    routePracticePitchHandler: any;
}

const SalesPitch: React.FC<SalesPitchProps> = ({ salesPitch, routePracticePitchHandler }) => (
    <div className="p-4">
        <h2 className="text-lg font-bold mb-2">Sales Pitch (Generated by Minerva Sales Agent)</h2>
        <p className="whitespace-pre-wrap">{salesPitch}</p>
        <button className="my-4 bg-transparent hover:bg-blue-500 text-blue-700 font-semibold hover:text-white py-2 px-4 border border-blue-500 hover:border-transparent rounded" onClick={routePracticePitchHandler}>
            Practice Pitch (Record)
        </button>
    </div>
);

export default SalesPitch;